<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><!doctype html><html><head><meta charset="UTF-8"><title>Ops</title></head><body><h1>Legacy Ops Lab</h1><nav><a href="${pageContext.request.contextPath}/">Home</a> | <a href="${pageContext.request.contextPath}/settlements">Session Settlements</a> | <a href="${pageContext.request.contextPath}/file-import">File Import</a></nav><h2>Vendor 등록</h2><form method="post" action="${pageContext.request.contextPath}/ops/vendors"><input name="code" placeholder="code"><input name="name" placeholder="name"><input name="creditLimit" placeholder="creditLimit"><button>Insert</button></form><p>에러: code 중복, creditLimit 음수/문자/공백.</p><h2>Inventory 등록</h2><form method="post" action="${pageContext.request.contextPath}/ops/inventory"><input name="sku" placeholder="sku"><input name="name" placeholder="name"><input name="quantity" placeholder="quantity"><button>Insert</button></form><h2>Inventory 검색</h2><form method="get" action="${pageContext.request.contextPath}/ops"><input name="keyword" value="${keyword}" placeholder="keyword"><input name="sortColumn" value="${sortColumn}" placeholder="sortColumn raw SQL"><button>Search</button></form><table border="1"><tr><th>ID</th><th>SKU</th><th>Name</th><th>Qty</th></tr><c:forEach var="item" items="${inventory}"><tr><td>${item.id}</td><td>${item.sku}</td><td>${item.name}</td><td>${item.quantity}</td></tr></c:forEach></table><h2>Daily Error Batch Manual Trigger</h2>
<form method="post" action="${pageContext.request.contextPath}/batch-lab/run">
    <select name="pattern">
        <option value="daily">daily pattern</option>
        <option value="duplicate">duplicate vendor</option>
        <option value="inventory">negative inventory</option>
        <option value="status">broken status</option>
        <option value="number">number format</option>
        <option value="npe">null pointer</option>
    </select>
    <button type="submit">Run Pattern</button>
</form><h2>DB Queue</h2><form method="post" action="${pageContext.request.contextPath}/ops/jobs"><input name="jobType" placeholder="jobType"><input name="payload" placeholder="payload, e.g. SKU-BASE"><input name="forceErrorCode" placeholder="NPE / SQL / NEGATIVE_STOCK / empty"><button>Enqueue</button></form><table border="1"><tr><th>ID</th><th>Type</th><th>Payload</th><th>Status</th><th>Attempts</th><th>Force</th><th>Run</th></tr><c:forEach var="job" items="${jobs}"><tr><td>${job.id}</td><td>${job.jobType}</td><td>${job.payload}</td><td>${job.status}</td><td>${job.attemptCount}</td><td>${job.forceErrorCode}</td><td><form method="post" action="${pageContext.request.contextPath}/ops/jobs/${job.id}/run"><button>Run</button></form></td></tr></c:forEach></table><h2>Vendors</h2><table border="1"><tr><th>ID</th><th>Code</th><th>Name</th><th>Credit</th></tr><c:forEach var="vendor" items="${vendors}"><tr><td>${vendor.id}</td><td>${vendor.code}</td><td>${vendor.name}</td><td>${vendor.creditLimit}</td></tr></c:forEach></table></body></html>